from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from datetime import date

from word_manager import get_todays_word
from game_engine import get_rank_and_score, word_exists

app = FastAPI(title="Obsidian Game API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

#when the secret is generated by the backend
class DailyGuessRequest(BaseModel):
    guess_word: str

#when the secret is generated by frontend
class GuessRequest(BaseModel):
    secret_word: str
    guess_word: str

def get_puzzle_number() -> int:
    start = date(2026, 3, 18)
    return (date.today() - start).days + 1


@app.get("/")
def root():
    return {"status": "Obsidian API is running"}


@app.get("/daily-info")
def daily_info():
    secret, difficulty = get_todays_word("./data/word_list.txt")
    return {
        "puzzle_number": get_puzzle_number(),
        "date": str(date.today()),
        "difficulty": difficulty,
    }


#when the secret is generated by backend 
@app.post("/daily-guess")
def daily_guess(req: DailyGuessRequest):
    guess = req.guess_word.strip().lower()

    if not guess:
        raise HTTPException(status_code=400, detail="Guess cannot be empty")

    if not word_exists(guess):
        raise HTTPException(status_code=404, detail=f"'{guess}' not in vocabulary")

    secret, difficulty = get_todays_word("./data/word_list.txt")
    result = get_rank_and_score(secret_word=secret, guess_word=guess)

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    return {**result, "difficulty": difficulty}

#when the secret is generated by frontend
@app.post("/guess")
def guess(req: GuessRequest):
    guess = req.guess_word.strip().lower()

    if not guess:
        raise HTTPException(status_code=400, detail="Guess cannot be empty")

    if not word_exists(guess):
        raise HTTPException(status_code=404, detail=f"'{guess}' not in vocabulary")

    result = get_rank_and_score(secret_word=req.secret_word, guess_word=guess)

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    return result


@app.get("/check-word/{word}")
def check_word(word: str):
    return {"word": word.lower(), "exists": word_exists(word)}