from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from datetime import date
from word_manager import get_todays_word
from game_engine import get_rank_and_score, word_exists
from game_engine import get_rank_and_score, word_exists, get_word_by_rank

app = FastAPI(title="Obsidian Game API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

#when the secret is generated by the backend
class DailyGuessRequest(BaseModel):
    guess_word: str

#when the secret is generated by frontend
class GuessRequest(BaseModel):
    secret_word: str
    guess_word: str

class HintRequest(BaseModel):
    best_rank : int
    hints_used : int


def get_puzzle_number() -> int:
    start = date(2026, 3, 18)
    return (date.today() - start).days + 1


@app.get("/")
def root():
    return {"status": "Obsidian API is running"}


@app.get("/daily-info")
def daily_info():
    secret, difficulty = get_todays_word("./data/word_list.txt")
    return {
        "puzzle_number": get_puzzle_number(),
        "date": str(date.today()),
        "difficulty": difficulty,
    }


#when the secret is generated by backend 
@app.post("/daily-guess")
def daily_guess(req: DailyGuessRequest):
    guess = req.guess_word.strip().lower()

    if not guess:
        raise HTTPException(status_code=400, detail="Guess cannot be empty")

    if not word_exists(guess):
        raise HTTPException(status_code=404, detail=f"'{guess}' not in vocabulary")

    secret, difficulty = get_todays_word("./data/word_list.txt")
    result = get_rank_and_score(secret_word=secret, guess_word=guess)

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    return {**result, "difficulty": difficulty}

#when the secret is generated by frontend
@app.post("/guess")
def guess(req: GuessRequest):
    guess = req.guess_word.strip().lower()

    if not guess:
        raise HTTPException(status_code=400, detail="Guess cannot be empty")

    if not word_exists(guess):
        raise HTTPException(status_code=404, detail=f"'{guess}' not in vocabulary")

    result = get_rank_and_score(secret_word=req.secret_word, guess_word=guess)

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    return result


@app.get("/check-word/{word}")
def check_word(word: str):
    return {"word": word.lower(), "exists": word_exists(word)}

@app.post("/hint")
def get_hint(request: HintRequest):
    
    # Max 3 hints allowed
    if request.hints_used >= 3:
        raise HTTPException(status_code=400, detail="No hints remaining")

    # Hint rank = best rank - 5 (closer to target word which is rank 1)
    hint_rank = request.best_rank - 5

    # Rank can't go below 1 (that would be the answer itself)
    if hint_rank < 1:
        hint_rank = 1

    secret, difficulty = get_todays_word("./data/word_list.txt")

    hint_word = get_word_by_rank(secret, hint_rank)

    return {
        "hint_word": hint_word,
        "hint_rank": hint_rank,
        "hints_remaining": 3 - (request.hints_used + 1)
    }